package EncuestaDeVotacion.encuesta;

import java.util.List;

import org.uqbar.commons.model.AbstractAutogeneratedIdHome;
import org.uqbar.commons.utils.Home;

public class HomeZonas extends AbstractAutogeneratedIdHome<Zona> {
	private static HomeZonas instance = new HomeZonas();

	public static HomeZonas homeZonas() {
		return instance;
	}
	
	public HomeZonas() {
		this.init();
	}
	
	public void init(){
		Zona caba = new Zona("CABA");
		caba.agregarCandidato("Horacio Rodriguez Larreta","PRO");
		caba.agregarCandidato("Martín Lousteau","Eco");
		caba.agregarCandidato("Gabriela Michetti","PRO");
		caba.agregarCandidato("Miriam Bregman","Frente de Izquierda");
		
		Zona bsas = new Zona("Buenos Aires");
		bsas.agregarCandidato("Aníbal Fernandez","FpV");
		bsas.agregarCandidato("Julian Dominguez","FpV");
		bsas.agregarCandidato("María Eugenia Vidal","PRO");
		
		Zona nacional = new Zona("Elección Nacional");
		nacional.agregarCandidato("Sergio Massa","Frente Renovador");
		nacional.agregarCandidato("Mauricio Macri","PRO");
		nacional.agregarCandidato("Daniel Scioli","FpV");
		
		this.create(caba);
		this.create(bsas);
		this.create(nacional);
	}

	public Class<Zona> getEntityType() {
		// TODO Auto-generated method stub
		return null;
	}

	public Zona searchById(int id) {
		// TODO Auto-generated method stub
		return null;
	}

	public List<Zona> searchByExample(Zona example) {
		// TODO Auto-generated method stub
		return null;
	}

	public Zona createExample() {
		// TODO Auto-generated method stub
		return null;
	}

	public List<Zona> allInstances() {
		// TODO Auto-generated method stub
		return null;
	}

	public void update(Zona object) {
		// TODO Auto-generated method stub
		
	}

	@Override
	protected void effectiveCreate(Zona object) {
		// TODO Auto-generated method stub
		
	}

	@Override
	protected void effectiveDelete(Zona object) {
		// TODO Auto-generated method stub
		
	}

}
