package EncuestaDeVotacion.encuesta;

import org.uqbar.commons.model.AbstractAutogeneratedIdHome;
import org.uqbar.commons.model.Entity;
import org.uqbar.commons.utils.Observable;

@Observable
public class Zona extends Entity{
	String descripcion;
	
	public Zona(String descripcion){
		this.descripcion = descripcion;
	}
	
	public String getDescripcion() {
		return descripcion;
	}
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	public AbstractAutogeneratedIdHome<Candidato> getCandidatos() {
		return candidatos;
	}
	public void setCandidatos(AbstractAutogeneratedIdHome<Candidato> candidatos) {
		this.candidatos = candidatos;
	}
	public void agregarCandidato(String nombre, String partido){
		this.candidatos.create(new Candidato(nombre,partido));
	}
}
